routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('task', 'TasksController');

Route::get('/', function () {
    return redirect ()->route('task.index');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Http\Traits\TimestampsTrait;
use App\Http\Traits\TasksTrait;

class Task extends Model
{
    use TimestampsTrait;
    use TasksTrait;

    public function getDates(){
        return ['created_at', 'updated_at','due_date'];
    }
    //Define the table
    protected $table ='tasks';


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;


use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::orderBy('due_date','asc')->paginate(2); 

        return view('tasks.index')->with('tasks', $tasks);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('tasks.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate The Data
        $this->validate($request, [
            'name' => 'required|string|max:255|min:3',
            'description' => 'required|string|max:10000|min:10',
            'due_date' => 'required|date',
        ]);
        //Create a new task
        $task = new Task;

        //Assign the task data from our request
        $task->name = $request->name;
        $task->description = $request->description;
        $task->due_date = $request->due_date;

        //Save the task
        $task->save();

        //Flash Session Messagge with success
        Session::flash('success', 'Created Task Successfully');

        //Return a Redirect
        return redirect()->route('task.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function show($id)
    {
        //Search the task with the id
        //Return a view (show.blade.php)
        //Pass with the return the variable that contains the specific task
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function edit($id)
    {
        $task = Task::find($id);
        $task->dueDateFormatting = false;

        return view('tasks.edit')->withTask($task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function update(Request $request, $id)
    {
         //Validate The Data
         $this->validate($request, [
            'name' => 'required|string|max:255|min:3',
            'description' => 'required|string|max:10000|min:10',
            'due_date' => 'required|date',
        ]);
        //Find the related task
        $task = Task::find($id);

        //Assign the task data from our request
        $task->name = $request->name;
        $task->description = $request->description;
        $task->due_date = $request->due_date;

        //Save the task
        $task->save();

        //Flash Session Messagge with success
        Session::flash('success', 'Saved the Task Successfully');

        //Return a Redirect
        return redirect()->route('task.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */


    public function destroy($id)
    {
        //Finding the specific task by ID
        $task = Task::find($id);

        //Deleting the task
        $task->delete();

        //flashing a sessioin message
        Session::flash('success', 'Deleted the task successfully');

        //Returning a redirect back to index
        return redirect()->route('task.index');
    }
}

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo List App - @yield('title')</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <style>
        .pagination{
           justify-content: center;
        }
    </style>

</head>
<body>
    
    <div class="container mt-3">
        @include('partials._messagges')

        @yield('content')
    </div>






    {{-- Bootstrap JS --}}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>
</body>
</html>

resources/views/partials/_messagges.blade.php
{{-- Primary Alert --}}
@if(Session::has('primary'))
	<div class="alert alert-primary alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('primary') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Secondary Alert --}}
@if(Session::has('secondary'))
	<div class="alert alert-secondary alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('secondary') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Success Alert --}}
@if(Session::has('success'))
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<strong>Success:</strong> {{ Session::get('success') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Danger Alert --}}
@if(Session::has('danger'))
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Error:</strong> {{ Session::get('danger') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Warning Alert --}}
@if(Session::has('warning'))
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<strong>Something Went Wrong!</strong>
		<br>
		{{ Session::get('warning') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Informational Alert --}}
@if(Session::has('info'))
	<div class="alert alert-info alert-dismissible fade show" role="alert">
		<strong>Heads Up!</strong> {{ Session::get('info') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Light Alert --}}
@if(Session::has('light'))
	<div class="alert alert-light alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('light') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Dark Alert --}}
@if(Session::has('dark'))
	<div class="alert alert-dark alert-dismissible fade show" role="alert">
		<strong>Note to User:</strong> {{ Session::get('dark') }}

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
@endif

{{-- Authentication Alerts --}}
@if (session('status'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
	<strong>Note to User:</strong> {{ session('status') }}

	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
@endif

{{-- If the page has any errors passed to it --}}
@if(count($errors) > 0)

	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<strong>Errors:</strong>

		<ul>
			@foreach($errors->all() as $error)
				
				<li>{{ $error }}</li>

			@endforeach
		</ul>

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>

@endif

resources/views/tasks/create.blade.php
@extends('layouts.main')

@section('title', 'Create Task')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1>Create Task</h1>

            {!! Form::open(['route' => 'task.store', 'method' => 'STORE']) !!}
                @component('components.taskForm')
                @endcomponent
            {!! Form::close() !!}
        </div>
    </div>
    
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Task')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1>Edit Task</h1>

            {!! Form::model($task, ['route' => ['task.update',$task->id], 'method' => 'PUT']) !!}
                @component('components.taskForm')
                @endcomponent
            {!! Form::close() !!}
        </div>
    </div>
    
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.main')

@section('title', 'Tasks Home')

@section('content')

    <div class="row justify-content-center mb-3">
        <div class="col-sm-4">
            <a href="{{ route('task.create') }}" class="btn btn-block btn-success">Create Task</a>
        </div>
    </div>
   
    @if ($tasks->count()==0)

        <p class="lead text-center">There are no tasks listed. Why don't create one!</p>
    
    @else 
        @foreach ($tasks as $task)

        <div class="row">
            <div class="col-sm-12">
                <h3>
                    {{ $task-> name }}
                    <small>{{ $task-> created_at }}</small>
                </h3>
                <p>{{ $task-> description }}</p>
                <h4>Due Date: <small>{{ $task-> due_date }}</small></h4>
                
                {!! Form::open(['route' => ['task.destroy', $task->id] , 'method' => 'DELETE']) !!}               
                    <a href="{{ route('task.edit', $task->id) }}" class="btn btn-sm btn-primary">Edit</a>
                    <button type="submit" class="btn btn-small btn-danger">Delete</button>

                {!! Form::close() !!}
            </div>
        </div>
        <hr>
    @endforeach

    @endif
   
    <div class="row justify-content-center">
        <div class="col-sm-6 text-center">
            {{ $tasks->links() }}
        </div>
    </div>
    
@endsection